---
engines:
  shellcheck:
    enabled: true

  scalastyle:
    enabled: true

  csslint:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - scala

  eslint:
    enabled: true

  fixme:
    enabled: true

ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.scala"

exclude_paths: []
