language: scala

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - unzip

jdk:
  - oraclejdk8

before_script:
  - "./setup.sh"

script: activator-1.3.10-minimal/bin/activator
