language: scala

sudo: false

addons:
  apt:
    packages:
      - unzip

jdk:
  - oraclejdk8

before_script:
  - "./setup.sh"

before_install: unset SBT_OPTS JVM_OPTS

script: activator-1.3.10-minimal/bin/activator stage
